#!/bin/sh
#. ./config-check.sh
ABSL_INSTALL=${INSTALLDIR}/abseil
cmake -S .. \
	-B .    \
	-G Ninja \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DCMAKE_CXX_STANDARD=17 \
    -DABSL_ENABLE_INSTALL=ON \
    -DCMAKE_INSTALL_PREFIX=${ABSL_INSTALL} \
	-DBUILD_SHARED_LIBS=ON \
	-DCMAKE_BUILD_TYPE=Release    
